version: '3'
services:
  app-container:
    build:
      context: .
    command: npm run coverage
    environment:
      DEBUG: app-container*
      NODE_ENV: test
    volumes:
     - .:/home/app/src
     - /home/app/src/node_modules
